/**
 * @file omni_robot.h
 *
 * @brief This header file was generated by cantools version 41.1.1 Mon Mar  9 02:46:55 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef OMNI_ROBOT_H
#define OMNI_ROBOT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define OMNI_ROBOT_MCU_STATUS_1_FRAME_ID (0x101u)
#define OMNI_ROBOT_MCU_STATUS_2_FRAME_ID (0x102u)
#define OMNI_ROBOT_MCU_STATUS_3_FRAME_ID (0x103u)
#define OMNI_ROBOT_MCU_STATUS_4_FRAME_ID (0x104u)
#define OMNI_ROBOT_MCU_STATUS_5_FRAME_ID (0x105u)
#define OMNI_ROBOT_MCU_STATUS_6_FRAME_ID (0x106u)
#define OMNI_ROBOT_R_PI_COMMAND_1_FRAME_ID (0x201u)
#define OMNI_ROBOT_R_PI_COMMAND_2_FRAME_ID (0x202u)
#define OMNI_ROBOT_R_PI_COMMAND_3_FRAME_ID (0x203u)
#define OMNI_ROBOT_R_PI_COMMAND_4_FRAME_ID (0x204u)
#define OMNI_ROBOT_R_PI_COMMAND_5_FRAME_ID (0x205u)
#define OMNI_ROBOT_R_PI_COMMAND_6_FRAME_ID (0x206u)
#define OMNI_ROBOT_R_PI_RECONFIG_FRAME_ID (0x300u)
#define OMNI_ROBOT_MCU_FAULT_FRAME_ID (0x10fu)
#define OMNI_ROBOT_R_PI_FAULT_CLEAR_FRAME_ID (0x301u)

/* Frame lengths in bytes. */
#define OMNI_ROBOT_MCU_STATUS_1_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_2_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_3_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_4_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_5_LENGTH (8u)
#define OMNI_ROBOT_MCU_STATUS_6_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_1_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_2_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_3_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_4_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_5_LENGTH (8u)
#define OMNI_ROBOT_R_PI_COMMAND_6_LENGTH (8u)
#define OMNI_ROBOT_R_PI_RECONFIG_LENGTH (6u)
#define OMNI_ROBOT_MCU_FAULT_LENGTH (4u)
#define OMNI_ROBOT_R_PI_FAULT_CLEAR_LENGTH (1u)

/* Extended or standard frame types. */
#define OMNI_ROBOT_MCU_STATUS_1_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_2_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_3_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_4_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_5_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_STATUS_6_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_1_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_2_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_3_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_4_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_5_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_COMMAND_6_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_RECONFIG_IS_EXTENDED (0)
#define OMNI_ROBOT_MCU_FAULT_IS_EXTENDED (0)
#define OMNI_ROBOT_R_PI_FAULT_CLEAR_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define OMNI_ROBOT_MCU_STATUS_1_NAME "MCU_Status_1"
#define OMNI_ROBOT_MCU_STATUS_2_NAME "MCU_Status_2"
#define OMNI_ROBOT_MCU_STATUS_3_NAME "MCU_Status_3"
#define OMNI_ROBOT_MCU_STATUS_4_NAME "MCU_Status_4"
#define OMNI_ROBOT_MCU_STATUS_5_NAME "MCU_Status_5"
#define OMNI_ROBOT_MCU_STATUS_6_NAME "MCU_Status_6"
#define OMNI_ROBOT_R_PI_COMMAND_1_NAME "RPi_Command_1"
#define OMNI_ROBOT_R_PI_COMMAND_2_NAME "RPi_Command_2"
#define OMNI_ROBOT_R_PI_COMMAND_3_NAME "RPi_Command_3"
#define OMNI_ROBOT_R_PI_COMMAND_4_NAME "RPi_Command_4"
#define OMNI_ROBOT_R_PI_COMMAND_5_NAME "RPi_Command_5"
#define OMNI_ROBOT_R_PI_COMMAND_6_NAME "RPi_Command_6"
#define OMNI_ROBOT_R_PI_RECONFIG_NAME "RPi_Reconfig"
#define OMNI_ROBOT_MCU_FAULT_NAME "MCU_Fault"
#define OMNI_ROBOT_R_PI_FAULT_CLEAR_NAME "RPi_FaultClear"

/* Signal Names. */
#define OMNI_ROBOT_MCU_STATUS_1_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_1_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_1_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_1_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_2_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_2_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_2_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_2_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_3_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_3_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_3_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_3_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_4_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_4_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_4_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_4_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_5_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_5_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_5_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_5_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_MCU_STATUS_6_JOINT_ANGLE_DEG_NAME "JointAngle_deg"
#define OMNI_ROBOT_MCU_STATUS_6_JOINT_VOLTAGE_M_V_NAME "JointVoltage_mV"
#define OMNI_ROBOT_MCU_STATUS_6_JOINT_TEMP_C_NAME "JointTemp_C"
#define OMNI_ROBOT_MCU_STATUS_6_TORQUE_ENABLED_NAME "TorqueEnabled"
#define OMNI_ROBOT_R_PI_COMMAND_1_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_1_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_1_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_1_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_2_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_2_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_2_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_2_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_3_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_3_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_3_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_3_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_4_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_4_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_4_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_4_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_5_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_5_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_5_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_5_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_COMMAND_6_TARGET_ANGLE_DEG_NAME "TargetAngle_deg"
#define OMNI_ROBOT_R_PI_COMMAND_6_MOVE_DURATION_MS_NAME "MoveDuration_ms"
#define OMNI_ROBOT_R_PI_COMMAND_6_TORQUE_ENABLE_NAME "TorqueEnable"
#define OMNI_ROBOT_R_PI_COMMAND_6_STOP_CMD_NAME "StopCmd"
#define OMNI_ROBOT_R_PI_RECONFIG_SERVO_ID_1_NAME "ServoId_1"
#define OMNI_ROBOT_R_PI_RECONFIG_SERVO_ID_2_NAME "ServoId_2"
#define OMNI_ROBOT_R_PI_RECONFIG_SERVO_ID_3_NAME "ServoId_3"
#define OMNI_ROBOT_R_PI_RECONFIG_SERVO_ID_4_NAME "ServoId_4"
#define OMNI_ROBOT_R_PI_RECONFIG_SERVO_ID_5_NAME "ServoId_5"
#define OMNI_ROBOT_R_PI_RECONFIG_SERVO_ID_6_NAME "ServoId_6"
#define OMNI_ROBOT_MCU_FAULT_MOTOR_ID_NAME "MotorId"
#define OMNI_ROBOT_MCU_FAULT_FAULT_CODE_NAME "FaultCode"
#define OMNI_ROBOT_MCU_FAULT_FAULT_VALUE_NAME "FaultValue"
#define OMNI_ROBOT_R_PI_FAULT_CLEAR_MOTOR_ID_NAME "MotorId"

/**
 * Signals in message MCU_Status_1.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_1_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_2.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_2_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_3.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_3_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_4.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_4_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_5.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_5_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message MCU_Status_6.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_status_6_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t joint_angle_deg;

    /**
     * Range: 0..65535 (0..65535 mV)
     * Scale: 1
     * Offset: 0
     */
    uint16_t joint_voltage_m_v;

    /**
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t joint_temp_c;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enabled;
};

/**
 * Signals in message RPi_Command_1.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_1_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_2.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_2_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_3.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_3_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_4.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_4_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_5.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_5_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Command_6.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_command_6_t {
    /**
     * Range: 0..36000 (0..360 deg)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t target_angle_deg;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t move_duration_ms;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t torque_enable;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_cmd;
};

/**
 * Signals in message RPi_Reconfig.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_reconfig_t {
    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t servo_id_1;

    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t servo_id_2;

    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t servo_id_3;

    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t servo_id_4;

    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t servo_id_5;

    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t servo_id_6;
};

/**
 * Signals in message MCU_Fault.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_mcu_fault_t {
    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t motor_id;

    /**
     * Range: 0..4 (0..4 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fault_code;

    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t fault_value;
};

/**
 * Signals in message RPi_FaultClear.
 *
 * All signal values are as on the CAN bus.
 */
struct omni_robot_r_pi_fault_clear_t {
    /**
     * Range: 0..6 (0..6 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t motor_id;
};

/**
 * Pack message MCU_Status_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_1_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_1_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_1_unpack(
    struct omni_robot_mcu_status_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_1_init(struct omni_robot_mcu_status_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_1_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_1_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_1_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_1_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_1_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_1_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_2_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_2_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_2_unpack(
    struct omni_robot_mcu_status_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_2_init(struct omni_robot_mcu_status_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_2_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_2_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_2_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_2_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_2_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_2_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_3_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_3_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_3_unpack(
    struct omni_robot_mcu_status_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_3_init(struct omni_robot_mcu_status_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_3_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_3_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_3_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_3_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_3_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_3_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_4_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_4_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_4_unpack(
    struct omni_robot_mcu_status_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_4_init(struct omni_robot_mcu_status_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_4_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_4_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_4_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_4_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_4_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_4_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_5.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_5_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_5_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_5.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_5_unpack(
    struct omni_robot_mcu_status_5_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_5.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_5_init(struct omni_robot_mcu_status_5_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_5_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_5_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_5_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_5_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_5_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_5_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_5_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_5_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_5_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_5_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_5_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_5_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message MCU_Status_6.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_status_6_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_status_6_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Status_6.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_status_6_unpack(
    struct omni_robot_mcu_status_6_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Status_6.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_status_6_init(struct omni_robot_mcu_status_6_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_6_joint_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_6_joint_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_6_joint_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_status_6_joint_voltage_m_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_6_joint_voltage_m_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_6_joint_voltage_m_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_6_joint_temp_c_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_6_joint_temp_c_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_6_joint_temp_c_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_status_6_torque_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_status_6_torque_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_status_6_torque_enabled_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_1_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_1_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_1_unpack(
    struct omni_robot_r_pi_command_1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_1_init(struct omni_robot_r_pi_command_1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_1_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_1_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_1_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_1_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_1_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_1_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_2_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_2_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_2_unpack(
    struct omni_robot_r_pi_command_2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_2_init(struct omni_robot_r_pi_command_2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_2_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_2_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_2_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_2_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_2_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_2_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_3_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_3_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_3_unpack(
    struct omni_robot_r_pi_command_3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_3_init(struct omni_robot_r_pi_command_3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_3_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_3_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_3_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_3_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_3_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_3_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_4.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_4_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_4_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_4.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_4_unpack(
    struct omni_robot_r_pi_command_4_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_4.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_4_init(struct omni_robot_r_pi_command_4_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_4_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_4_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_4_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_4_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_4_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_4_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_5.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_5_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_5_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_5.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_5_unpack(
    struct omni_robot_r_pi_command_5_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_5.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_5_init(struct omni_robot_r_pi_command_5_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_5_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_5_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_5_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_5_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_5_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_5_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_5_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_5_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_5_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_5_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_5_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_5_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Command_6.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_command_6_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_command_6_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Command_6.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_command_6_unpack(
    struct omni_robot_r_pi_command_6_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Command_6.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_command_6_init(struct omni_robot_r_pi_command_6_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_6_target_angle_deg_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_6_target_angle_deg_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_6_target_angle_deg_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_r_pi_command_6_move_duration_ms_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_6_move_duration_ms_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_6_move_duration_ms_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_6_torque_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_6_torque_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_6_torque_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_command_6_stop_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_command_6_stop_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_command_6_stop_cmd_is_in_range(uint8_t value);

/**
 * Pack message RPi_Reconfig.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_reconfig_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_reconfig_t *src_p,
    size_t size);

/**
 * Unpack message RPi_Reconfig.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_reconfig_unpack(
    struct omni_robot_r_pi_reconfig_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_Reconfig.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_reconfig_init(struct omni_robot_r_pi_reconfig_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_reconfig_servo_id_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_reconfig_servo_id_1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_reconfig_servo_id_1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_reconfig_servo_id_2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_reconfig_servo_id_2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_reconfig_servo_id_2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_reconfig_servo_id_3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_reconfig_servo_id_3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_reconfig_servo_id_3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_reconfig_servo_id_4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_reconfig_servo_id_4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_reconfig_servo_id_4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_reconfig_servo_id_5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_reconfig_servo_id_5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_reconfig_servo_id_5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_reconfig_servo_id_6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_reconfig_servo_id_6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_reconfig_servo_id_6_is_in_range(uint8_t value);

/**
 * Pack message MCU_Fault.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_mcu_fault_pack(
    uint8_t *dst_p,
    const struct omni_robot_mcu_fault_t *src_p,
    size_t size);

/**
 * Unpack message MCU_Fault.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_mcu_fault_unpack(
    struct omni_robot_mcu_fault_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MCU_Fault.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_mcu_fault_init(struct omni_robot_mcu_fault_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_fault_motor_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_fault_motor_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_fault_motor_id_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_mcu_fault_fault_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_fault_fault_code_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_fault_fault_code_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t omni_robot_mcu_fault_fault_value_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_mcu_fault_fault_value_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_mcu_fault_fault_value_is_in_range(uint16_t value);

/**
 * Pack message RPi_FaultClear.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int omni_robot_r_pi_fault_clear_pack(
    uint8_t *dst_p,
    const struct omni_robot_r_pi_fault_clear_t *src_p,
    size_t size);

/**
 * Unpack message RPi_FaultClear.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int omni_robot_r_pi_fault_clear_unpack(
    struct omni_robot_r_pi_fault_clear_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RPi_FaultClear.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int omni_robot_r_pi_fault_clear_init(struct omni_robot_r_pi_fault_clear_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t omni_robot_r_pi_fault_clear_motor_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double omni_robot_r_pi_fault_clear_motor_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool omni_robot_r_pi_fault_clear_motor_id_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
